import json
import os

all_languages = {
    "en": {
        "intake": {
            "title": "Citizen Concessional Credit Intake (Step 1 of 4)",
            "subtitle": "Please answer all 11 statutory eligibility questions below on this single page. You can click 🔊 to listen to any question in English or click 🎙️ on any answer field to speak your response.",
            "progress": "Step 1 of 4 • Identity & Project Assessment",
            "listenAll": "🔊 Listen to Page Instructions",
            "micListening": "🎙️ Listening... Please speak now in",
            "listeningActive": "Listening Live",
            "clickToStop": "Click to stop recording",
            "voiceAutoFilled": "✓ Speech recognized and auto-filled successfully!",
            "q1_title": "1. Enter your Full Name and Mobile Number",
            "q1_desc": "Please provide your official legal name and Aadhaar-linked 10-digit mobile number.",
            "nameLabel": "Full Legal Name",
            "namePlaceholder": "e.g. Rajesh Kumar SC",
            "phoneLabel": "Mobile / Contact Number",
            "phonePlaceholder": "e.g. +91 98480 12345",
            "genderLabel": "Applicant Gender (Determines Special Women Interest Concession)",
            "genderFemale": "Female (Special Concessional 5% Rate)",
            "genderMale": "Male (Standard 6.5% - 7.5% Rate)",
            "genderOther": "Transgender / Other",
            "q2_title": "2. Enter your Age / Date of Birth",
            "q2_desc": "Select your birth date using the calendar or enter your age directly.",
            "dobLabel": "Date of Birth (Calendar)",
            "ageLabel": "Calculated Age",
            "yearsOld": "Years Old",
            "q3_title": "3. State / Union Territory",
            "q3_desc": "Select the Indian State or Union Territory where the project/business will operate.",
            "selectState": "-- Select Indian State / UT --",
            "q4_title": "4. District",
            "q4_desc": "Select the district for local State Channelizing Agency (SCA) or Bank Branch routing.",
            "selectDistrict": "-- Select District --",
            "q5_title": "5. Location & Postal PIN Code",
            "q5_desc": "Detect your exact GPS location or enter your village/town address and 6-digit postal PIN code.",
            "detectGps": "📍 Detect My Current GPS Location",
            "detectingGps": "Detecting satellite coordinates...",
            "gpsSuccess": "✓ GPS Location Acquired:",
            "manualAddress": "Village / Town / Street Address",
            "addressPlaceholder": "Enter local street, village or town address",
            "pincodeLabel": "Postal PIN Code (6-digits)",
            "pincodePlaceholder": "e.g. 533001",
            "q6_title": "6. Do you belong to Scheduled Caste (SC) Community?",
            "q6_desc": "NSFDC schemes are statutory concessional loan programs reserved exclusively for Scheduled Caste beneficiaries.",
            "yesSc": "✓ Yes, I belong to Scheduled Caste (SC)",
            "noSc": "✗ No, Other Community",
            "scWarning": "⚠️ Statutory Note: NSFDC concessional loans are strictly designated for Scheduled Caste (SC) citizens as per Ministry of Social Justice & Empowerment guidelines. A valid SC caste certificate will be verified in Step 2.",
            "q7_title": "7. Educational Qualifications",
            "q7_desc": "Select your highest completed educational level. If not listed, select 'Other' and specify.",
            "selectQualification": "-- Select Educational Qualification --",
            "otherQualLabel": "Please specify your qualification:",
            "otherQualPlaceholder": "e.g. Diploma in Mechanical, B.Com Computer Applications",
            "q8_title": "8. Annual Family Income (₹)",
            "q8_desc": "Enter total annual family income from all sources. Statutory Hard Gate ceiling is ₹ 5,00,000 / year.",
            "incomeLabel": "Annual Family Income (in Rupees)",
            "incomePlaceholder": "e.g. 180000",
            "incomeLimitBadge": "Statutory Hard Gate Ceiling: ₹ 5,00,000.00 / year",
            "incomeWarning": "⚠️ Alert: Annual income exceeds ₹ 5,00,000 statutory limit. Beneficiary will not be eligible under NSFDC rules.",
            "incomeQuick": "Quick Select:",
            "q9_title": "9. What type of assistance are you looking for?",
            "q9_desc": "Select the primary category of financial assistance or scheme purpose you require.",
            "selectAssistance": "-- Select Assistance / Loan Purpose --",
            "subBusinessTitle": "↳ Specify Type of Business / Enterprise",
            "subBusinessDesc": "Select your trade activity to match sector-specific concessional guidelines.",
            "selectBusiness": "-- Select Business Sector / Trade --",
            "otherAssistLabel": "Please specify the assistance requirement:",
            "otherAssistPlaceholder": "e.g. Mobile repair and accessories shop",
            "otherBizLabel": "Please specify your business activity:",
            "otherBizPlaceholder": "e.g. Organic spice packaging unit",
            "q10_title": "10. Do you already have any existing loan for this project?",
            "q10_desc": "Disclose any prior or existing institutional credit availed for the current enterprise.",
            "yesLoan": "Yes, I have an existing loan",
            "noLoan": "No, this is a fresh loan application",
            "existingAmountLabel": "Original Sanctioned Loan Amount (₹)",
            "existingAmountPlaceholder": "e.g. 50000",
            "outstandingAmountLabel": "Current Outstanding / Balance Amount (₹)",
            "outstandingAmountPlaceholder": "e.g. 20000",
            "q11_title": "11. Project Estimated Cost (₹)",
            "q11_desc": "Enter the total capital cost required. NSFDC finances up to 90% - 95% with 5% - 10% beneficiary margin.",
            "costLabel": "Total Project Requirement (in Rupees)",
            "costPlaceholder": "e.g. 140000",
            "costQuick": "Quick Select:",
            "govtSharePreview": "Estimated Government Loan (90-95%):",
            "marginPreview": "Estimated Beneficiary Margin (5-10%):",
            "proceedStep2": "Proceed to Step 2: SC Certificate OCR Verification →",
            "viewFormalApp": "📄 View Formal Government Application Form",
            "validationAlert": "Please complete all mandatory fields (Name, Phone, State, District, SC status, Income, and Cost) to continue."
        }
    },
    "te": {
        "intake": {
            "title": "పౌర రాయితీ రుణ దరఖాస్తు (దశ 1 / 4)",
            "subtitle": "దయచేసి ఈ ఒకే పేజీలో క్రింది 11 చట్టబద్ధమైన అర్హత ప్రశ్నలకు సమాధానం ఇవ్వండి. ప్రశ్నను తెలుగులో వినడానికి 🔊 క్లిక్ చేయండి లేదా మీ సమాధానం మాట్లాడటానికి 🎙️ క్లిక్ చేయండి.",
            "progress": "దశ 1 / 4 • గుర్తింపు మరియు ప్రాజెక్ట్ అంచనా",
            "listenAll": "🔊 పేజీ సూచనలను వినండి",
            "micListening": "🎙️ వింటున్నాము... దయచేసి ఇప్పుడు తెలుగులో మాట్లాడండి",
            "listeningActive": "లైవ్ రికార్డింగ్ నడుస్తోంది",
            "clickToStop": "రికార్డింగ్ ఆపడానికి క్లిక్ చేయండి",
            "voiceAutoFilled": "✓ వాయిస్ గుర్తించబడింది మరియు విజయవంతంగా పూరించబడింది!",
            "q1_title": "1. మీ పూర్తి పేరు మరియు మొబైల్ నంబర్ నమోదు చేయండి",
            "q1_desc": "మీ అధికారిక పేరు మరియు ఆధార్-లింక్డ్ 10 అంకెల మొబైల్ నంబర్ ఇవ్వండి.",
            "nameLabel": "పూర్తి చట్టబద్ధమైన పేరు",
            "namePlaceholder": "ఉదా. రాజేష్ కుమార్ ఎస్సీ",
            "phoneLabel": "మొబైల్ / సంప్రదింపు నంబర్",
            "phonePlaceholder": "ఉదా. +91 98480 12345",
            "genderLabel": "లబ్ధిదారుని లింగం (మహిళలకు ప్రత్యేక 5% రాయితీ వర్తిస్తుంది)",
            "genderFemale": "మహిళ (ప్రత్యేక 5% రాయితీ వడ్డీ రేటు)",
            "genderMale": "పురుషుడు (ప్రామాణిక 6.5% - 7.5% వడ్డీ రేటు)",
            "genderOther": "ట్రాన్స్‌జెండర్ / ఇతరులు",
            "q2_title": "2. మీ వయస్సు / పుట్టిన తేదీని నమోదు చేయండి",
            "q2_desc": "క్యాలెండర్ ద్వారా మీ పుట్టిన తేదీని ఎంచుకోండి లేదా నేరుగా వయస్సు నమోదు చేయండి.",
            "dobLabel": "పుట్టిన తేదీ (క్యాలెండర్)",
            "ageLabel": "లెక్కించిన వయస్సు",
            "yearsOld": "సంవత్సరాలు",
            "q3_title": "3. రాష్ట్రం / కేంద్రపాలిత ప్రాంతం",
            "q3_desc": "ప్రాజెక్ట్/వ్యాపారం నిర్వహించబడే రాష్ట్రాన్ని ఎంచుకోండి.",
            "selectState": "-- రాష్ట్రాన్ని ఎంచుకోండి --",
            "q4_title": "4. జిల్లా",
            "q4_desc": "స్థానిక ఎస్సీ కార్పొరేషన్ (SCA) లేదా బ్యాంక్ బ్రాంచ్ రౌటింగ్ కోసం జిల్లాను ఎంచుకోండి.",
            "selectDistrict": "-- జిల్లాను ఎంచుకోండి --",
            "q5_title": "5. లొకేషన్ & పోస్టల్ పిన్ కోడ్",
            "q5_desc": "మీ ఖచ్చితమైన GPS లొకేషన్‌ను స్వయంచాలకంగా పొందండి లేదా చిరునామా మరియు పిన్ కోడ్ నమోదు చేయండి.",
            "detectGps": "📍 నా ప్రస్తుత GPS లొకేషన్‌ను గుర్తించండి",
            "detectingGps": "శాటిలైట్ కోఆర్డినేట్స్ గుర్తిస్తున్నాము...",
            "gpsSuccess": "✓ GPS లొకేషన్ విజయవంతంగా స్వీకరించబడింది:",
            "manualAddress": "గ్రామం / పట్టణం / వీధి చిరునామా",
            "addressPlaceholder": "స్థానిక చిరునామా, గ్రామం లేదా పట్టణాన్ని నమోదు చేయండి",
            "pincodeLabel": "పోస్టల్ పిన్ కోడ్ (6-అంకెలు)",
            "pincodePlaceholder": "ఉదా. 533001",
            "q6_title": "6. మీరు షెడ్యూల్డ్ కులం (SC) కమ్యూనిటీకి చెందినవారా?",
            "q6_desc": "NSFDC పథకాలు ప్రత్యేకంగా షెడ్యూల్డ్ కులాల లబ్ధిదారుల కోసం కేటాయించబడిన చట్టబద్ధమైన రాయితీ రుణ కార్యక్రమాలు.",
            "yesSc": "✓ అవును, నేను షెడ్యూల్డ్ కులం (SC) కి చెందినవాడిని/రాలిని",
            "noSc": "✗ కాదు, ఇతర వర్గం",
            "scWarning": "⚠️ చట్టబద్ధమైన గమనిక: కేంద్ర సామాజిక న్యాయ మంత్రిత్వ శాఖ మార్గదర్శకాల ప్రకారం NSFDC రాయితీ రుణాలు కేవలం SC పౌరులకు మాత్రమే. దశ 2 లో కుల ధృవీకరణ పత్రం ధృవీకరించబడుతుంది.",
            "q7_title": "7. విద్యా అర్హతలు",
            "q7_desc": "మీ అత్యున్నత విద్యార్హతను ఎంచుకోండి. జాబితాలో లేకపోతే 'ఇతర' ఎంచుకుని వివరించండి.",
            "selectQualification": "-- విద్యా అర్హతను ఎంచుకోండి --",
            "otherQualLabel": "దయచేసి మీ విద్యార్హతను వివరించండి:",
            "otherQualPlaceholder": "ఉదా. మెకానికల్ డిప్లొమా, బీకాం",
            "q8_title": "8. వార్షిక కుటుంబ ఆదాయం (₹)",
            "q8_desc": "అన్ని మార్గాల నుండి మొత్తం వార్షిక కుటుంబ ఆదాయం నమోదు చేయండి. చట్టబద్ధమైన పరిమితి ₹ 5,00,000 / సంవత్సరం.",
            "incomeLabel": "వార్షిక కుటుంబ ఆదాయం (రూపాయలలో)",
            "incomePlaceholder": "ఉదా. 180000",
            "incomeLimitBadge": "గరిష్ట చట్టబద్ధమైన ఆదాయ పరిమితి: ₹ 5,00,000.00 / సం.",
            "incomeWarning": "⚠️ హెచ్చరిక: వార్షిక ఆదాయం ₹ 5,00,000 పరిమితిని మించింది. NSFDC నిబంధనల ప్రకారం దరఖాస్తుదారు అర్హులు కారు.",
            "incomeQuick": "త్వరిత ఎంపిక:",
            "q9_title": "9. మీరు ఎలాంటి సహాయం కోరుకుంటున్నారు?",
            "q9_desc": "మీకు అవసరమైన ఆర్థిక సహాయం లేదా రుణ ప్రయోజనం యొక్క ప్రధాన వర్గాన్ని ఎంచుకోండి.",
            "selectAssistance": "-- సహాయం / రుణ ప్రయోజనాన్ని ఎంచుకోండి --",
            "subBusinessTitle": "↳ వ్యాపారం / పరిశ్రమ రకాన్ని పేర్కొనండి",
            "subBusinessDesc": "రంగాల వారీ రాయితీ మార్గదర్శకాల కోసం మీ వ్యాపార రకాన్ని ఎంచుకోండి.",
            "selectBusiness": "-- వ్యాపార రంగాన్ని ఎంచుకోండి --",
            "otherAssistLabel": "దయచేసి సహాయ అవసరాన్ని పేర్కొనండి:",
            "otherAssistPlaceholder": "ఉదా. మొబైల్ రిపేర్ మరియు ఉపకరణాల దుకాణం",
            "otherBizLabel": "దయచేసి మీ వ్యాపార కార్యకలాపాన్ని పేర్కొనండి:",
            "otherBizPlaceholder": "ఉదా. మసాలా ప్యాకేజింగ్ యూనిట్",
            "q10_title": "10. ఈ ప్రాజెక్ట్ కోసం మీకు ఇప్పటికే ఏదైనా రుణం ఉందా?",
            "q10_desc": "ప్రస్తుత వ్యాపారం కోసం తీసుకున్న ముందస్తు రుణ వివరాలను వెల్లడించండి.",
            "yesLoan": "అవును, నాకు ఇప్పటికే రుణం ఉంది",
            "noLoan": "లేదు, ఇది సరికొత్త రుణ దరఖాస్తు",
            "existingAmountLabel": "మంజూరైన అసలు రుణ మొత్తం (₹)",
            "existingAmountPlaceholder": "ఉదా. 50000",
            "outstandingAmountLabel": "ప్రస్తుత బకాయి / మిగిలిన మొత్తం (₹)",
            "outstandingAmountPlaceholder": "ఉదా. 20000",
            "q11_title": "11. ప్రాజెక్ట్ అంచనా వ్యయం (₹)",
            "q11_desc": "అవసరమైన మొత్తం మూలధన వ్యయాన్ని నమోదు చేయండి. NSFDC 90% నుండి 95% వరకు రుణం అందిస్తుంది (లబ్ధిదారుని వాటా 5% - 10%).",
            "costLabel": "మొత్తం ప్రాజెక్ట్ వ్యయం (రూపాయలలో)",
            "costPlaceholder": "ఉదా. 140000",
            "costQuick": "త్వరిత ఎంపిక:",
            "govtSharePreview": "అంచనా ప్రభుత్వ రుణం (90-95%):",
            "marginPreview": "అంచనా లబ్ధిదారుని వాటా (5-10%):",
            "proceedStep2": "దశ 2 కు వెళ్లండి: కుల ధృవీకరణ పత్రం OCR ధృవీకరణ →",
            "viewFormalApp": "📄 అధికారిక ప్రభుత్వ దరఖాస్తు ఫారమ్ చూడండి",
            "validationAlert": "దయచేసి ముందుకు సాగడానికి అన్ని తప్పనిసరి వివరాలను (పేరు, ఫోన్, రాష్ట్రం, జిల్లా, SC స్థితి, ఆదాయం మరియు ఖర్చు) పూరించండి."
        }
    },
    "hi": {
        "intake": {
            "title": "नागरिक रियायती ऋण आवेदन (चरण 1 / 4)",
            "subtitle": "कृपया इस एकल पृष्ठ पर नीचे दिए गए सभी 11 वैधानिक पात्रता प्रश्नों के उत्तर दें। आप किसी भी प्रश्न को हिन्दी में सुनने के लिए 🔊 पर क्लिक कर सकते हैं या अपना उत्तर बोलने के लिए 🎙️ पर क्लिक कर सकते हैं।",
            "progress": "चरण 1 / 4 • पहचान एवं परियोजना मूल्यांकन",
            "listenAll": "🔊 पृष्ठ निर्देश सुनें",
            "micListening": "🎙️ सुन रहे हैं... कृपया अब हिन्दी में बोलें",
            "listeningActive": "लाइव रिकॉर्डिंग सक्रिय",
            "clickToStop": "रिकॉर्डिंग रोकने के लिए क्लिक करें",
            "voiceAutoFilled": "✓ वाणी पहचानी गई और सफलतापूर्वक दर्ज की गई!",
            "q1_title": "1. अपना पूरा नाम और मोबाइल नंबर दर्ज करें",
            "q1_desc": "कृपया अपना आधिकारिक नाम और आधार से जुड़ा 10-अंकीय मोबाइल नंबर प्रदान करें।",
            "nameLabel": "पूरा कानूनी नाम",
            "namePlaceholder": "उदा. राजेश कुमार एससी",
            "phoneLabel": "मोबाइल / संपर्क नंबर",
            "phonePlaceholder": "उदा. +91 98480 12345",
            "genderLabel": "लाभार्थी का लिंग (महिला विशेष रियायती ब्याज दर निर्धारित करता है)",
            "genderFemale": "महिला (विशेष रियायती 5% दर)",
            "genderMale": "पुरुष (मानक 6.5% - 7.5% दर)",
            "genderOther": "ट्रांसजेंडर / अन्य",
            "q2_title": "2. अपनी आयु / जन्म तिथि दर्ज करें",
            "q2_desc": "कैलेंडर का उपयोग करके अपनी जन्म तिथि चुनें या अपनी आयु सीधे दर्ज करें।",
            "dobLabel": "जन्म तिथि (कैलेंडर)",
            "ageLabel": "गणना की गई आयु",
            "yearsOld": "वर्ष",
            "q3_title": "3. राज्य / केंद्र शासित प्रदेश",
            "q3_desc": "वह भारतीय राज्य या केंद्र शासित प्रदेश चुनें जहां परियोजना/व्यवसाय संचालित होगा।",
            "selectState": "-- भारतीय राज्य / केंद्र शासित प्रदेश चुनें --",
            "q4_title": "4. जिला",
            "q4_desc": "स्थानीय राज्य चैनलाइजिंग एजेंसी (एससीए) या बैंक शाखा रूटिंग के लिए जिला चुनें।",
            "selectDistrict": "-- जिला चुनें --",
            "q5_title": "5. स्थान एवं पोस्टल पिन कोड",
            "q5_desc": "अपना सटीक जीपीएस स्थान स्वतः प्राप्त करें या अपना गांव/शहर का पता और 6-अंकीय पिन कोड दर्ज करें।",
            "detectGps": "📍 मेरा वर्तमान जीपीएस स्थान स्वतः प्राप्त करें",
            "detectingGps": "उपग्रह निर्देशांक खोजे जा रहे हैं...",
            "gpsSuccess": "✓ जीपीएस स्थान सफलतापूर्वक प्राप्त हुआ:",
            "manualAddress": "गांव / कस्बा / सड़क का पता",
            "addressPlaceholder": "स्थानीय पता, गांव या कस्बे का नाम दर्ज करें",
            "pincodeLabel": "पोस्टल पिन कोड (6-अंक)",
            "pincodePlaceholder": "उदा. 533001",
            "q6_title": "6. क्या आप अनुसूचित जाति (SC) समुदाय से संबंधित हैं?",
            "q6_desc": "एनएसएफडीसी योजनाएं विशेष रूप से अनुसूचित जाति के लाभार्थियों के लिए आरक्षित वैधानिक रियायती ऋण कार्यक्रम हैं।",
            "yesSc": "✓ हाँ, मैं अनुसूचित जाति (SC) से हूँ",
            "noSc": "✗ नहीं, अन्य समुदाय",
            "scWarning": "⚠️ वैधानिक सूचना: सामाजिक न्याय एवं अधिकारिता मंत्रालय के दिशानिर्देशों के अनुसार एनएसएफडीसी रियायती ऋण केवल अनुसूचित जाति (SC) के नागरिकों के लिए हैं। चरण 2 में जाति प्रमाण पत्र सत्यापित किया जाएगा।",
            "q7_title": "7. शैक्षणिक योग्यता",
            "q7_desc": "अपनी उच्चतम पूर्ण शैक्षणिक योग्यता चुनें। यदि सूची में नहीं है, तो 'अन्य' चुनें और विवरण लिखें।",
            "selectQualification": "-- शैक्षणिक योग्यता चुनें --",
            "otherQualLabel": "कृपया अपनी योग्यता का विवरण दें:",
            "otherQualPlaceholder": "उदा. मैकेनिकल में डिप्लोमा, बी.कॉम",
            "q8_title": "8. वार्षिक पारिवारिक आय (₹)",
            "q8_desc": "सभी स्रोतों से कुल वार्षिक पारिवारिक आय दर्ज करें। वैधानिक सीमा ₹ 5,00,000 / वर्ष है।",
            "incomeLabel": "वार्षिक पारिवारिक आय (रुपये में)",
            "incomePlaceholder": "उदा. 180000",
            "incomeLimitBadge": "वैधानिक आय सीमा: ₹ 5,00,000.00 / वर्ष",
            "incomeWarning": "⚠️ चेतावनी: वार्षिक आय ₹ 5,00,000 की वैधानिक सीमा से अधिक है। एनएसएफडीसी नियमों के तहत लाभार्थी पात्र नहीं होगा।",
            "incomeQuick": "त्वरित चयन:",
            "q9_title": "9. आप किस प्रकार की सहायता की तलाश कर रहे हैं?",
            "q9_desc": "आवश्यक वित्तीय सहायता या ऋण उद्देश्य की मुख्य श्रेणी चुनें।",
            "selectAssistance": "-- सहायता / ऋण उद्देश्य चुनें --",
            "subBusinessTitle": "↳ व्यवसाय / उद्यम का प्रकार निर्दिष्ट करें",
            "subBusinessDesc": "क्षेत्र-विशिष्ट रियायती दिशानिर्देशों के मिलान के लिए अपनी व्यावसायिक गतिविधि चुनें।",
            "selectBusiness": "-- व्यवसाय क्षेत्र / व्यापार चुनें --",
            "otherAssistLabel": "कृपया सहायता की आवश्यकता का विवरण दें:",
            "otherAssistPlaceholder": "उदा. मोबाइल मरम्मत और सहायक उपकरण की दुकान",
            "otherBizLabel": "कृपया अपनी व्यावसायिक गतिविधि का विवरण दें:",
            "otherBizPlaceholder": "उदा. मसाला पैकेजिंग इकाई",
            "q10_title": "10. क्या आपके पास इस परियोजना के लिए पहले से कोई ऋण है?",
            "q10_desc": "वर्तमान उद्यम के लिए प्राप्त किसी भी पूर्व या मौजूदा संस्थागत ऋण का खुलासा करें।",
            "yesLoan": "हाँ, मेरे पास मौजूदा ऋण है",
            "noLoan": "नहीं, यह एक नया ऋण आवेदन है",
            "existingAmountLabel": "मूल स्वीकृत ऋण राशि (₹)",
            "existingAmountPlaceholder": "उदा. 50000",
            "outstandingAmountLabel": "वर्तमान बकाया / शेष राशि (₹)",
            "outstandingAmountPlaceholder": "उदा. 20000",
            "q11_title": "11. परियोजना की अनुमानित लागत (₹)",
            "q11_desc": "आवश्यक कुल पूंजीगत लागत दर्ज करें। एनएसएफडीसी 90% से 95% तक वित्तपोषित करता है जिसमें 5% से 10% लाभार्थी मार्जिन होता है।",
            "costLabel": "कुल परियोजना आवश्यकता (रुपये में)",
            "costPlaceholder": "उदा. 140000",
            "costQuick": "त्वरित चयन:",
            "govtSharePreview": "अनुमानित सरकारी ऋण (90-95%):",
            "marginPreview": "अनुमानित लाभार्थी मार्जिन (5-10%):",
            "proceedStep2": "चरण 2 पर आगे बढ़ें: जाति प्रमाण पत्र OCR सत्यापन →",
            "viewFormalApp": "📄 औपचारिक सरकारी आवेदन पत्र देखें",
            "validationAlert": "कृपया आगे बढ़ने के लिए सभी अनिवार्य फ़ील्ड (नाम, फोन, राज्य, जिला, एससी स्थिति, आय और लागत) भरें।"
        }
    },
    "ta": {
        "intake": {
            "title": "குடிமக்கள் மானிய கடன் விண்ணப்பம் (படி 1 / 4)",
            "subtitle": "தயவுசெய்து இந்த ஒற்றை பக்கத்தில் கீழே உள்ள 11 சட்டப்பூர்வ தகுதி வினாக்களுக்கு பதிலளிக்கவும். தமிழில் வினாவைக் கேட்க 🔊 கிளிக் செய்யவும் அல்லது உங்கள் பதிலை பேச 🎙️ கிளிக் செய்யவும்.",
            "progress": "படி 1 / 4 • அடையாளம் & திட்ட மதிப்பீடு",
            "listenAll": "🔊 பக்க வழிமுறைகளைக் கேளுங்கள்",
            "micListening": "🎙️ கேட்கிறது... இப்போது தமிழில் பேசுங்கள்",
            "listeningActive": "நேரடி பதிவு செயலில் உள்ளது",
            "clickToStop": "பதிவை நிறுத்த கிளிக் செய்யவும்",
            "voiceAutoFilled": "✓ பேச்சு அங்கீகரிக்கப்பட்டு வெற்றிகரமாக நிரப்பப்பட்டது!",
            "q1_title": "1. உங்கள் முழு பெயர் மற்றும் மொபைல் எண்ணை உள்ளிடவும்",
            "q1_desc": "உங்கள் அதிகாரப்பூர்வ பெயர் மற்றும் ஆதார் இணைக்கப்பட்ட 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
            "nameLabel": "முழு சட்டப்பூர்வ பெயர்",
            "namePlaceholder": "எ.கா. ராஜேஷ் குமார் எஸ்சி",
            "phoneLabel": "மொபைல் / தொடர்பு எண்",
            "phonePlaceholder": "எ.கா. +91 98480 12345",
            "genderLabel": "பயனாளி பாலினம் (பெண்களுக்கு 5% சிறப்பு மானிய வட்டி விகிதம்)",
            "genderFemale": "பெண் (சிறப்பு 5% மானிய வட்டி விகிதம்)",
            "genderMale": "ஆண் (நிலையான 6.5% - 7.5% வட்டி விகிதம்)",
            "genderOther": "திருநங்கை / பிற",
            "q2_title": "2. உங்கள் வயது / பிறந்த தேதியை உள்ளிடவும்",
            "q2_desc": "கேலெண்டரைப் பயன்படுத்தி உங்கள் பிறந்த தேதியைத் தேர்வுசெய்யவும் அல்லது வயதை உள்ளிடவும்.",
            "dobLabel": "பிறந்த தேதி (கேலெண்டர்)",
            "ageLabel": "கணக்கிடப்பட்ட வயது",
            "yearsOld": "வயது",
            "q3_title": "3. மாநிலம் / யூனியன் பிரதேசம்",
            "q3_desc": "திட்டம்/வணிகம் செயல்படும் இந்திய மாநிலத்தைத் தேர்ந்தெடுக்கவும்.",
            "selectState": "-- மாநிலத்தைத் தேர்ந்தெடுக்கவும் --",
            "q4_title": "4. மாவட்டம்",
            "q4_desc": "உள்ளூர் எஸ்சிஏ அல்லது வங்கி கிளை ரூட்டிங்கிற்கு மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.",
            "selectDistrict": "-- மாவட்டத்தைத் தேர்ந்தெடுக்கவும் --",
            "q5_title": "5. இருப்பிடம் & அஞ்சல் குறியீட்டு எண்",
            "q5_desc": "உங்கள் துல்லியமான ஜிபிஎஸ் இருப்பிடத்தைப் பெறவும் அல்லது முகவரியை உள்ளிடவும்.",
            "detectGps": "📍 எனது தற்போதைய ஜிபிஎஸ் இருப்பிடத்தைக் கண்டறியவும்",
            "detectingGps": "செயற்கைக்கோள் ஆயங்களை கண்டறிகிறது...",
            "gpsSuccess": "✓ ஜிபிஎஸ் இருப்பிடம் பெறப்பட்டது:",
            "manualAddress": "கிராமம் / நகரம் / தெரு முகவரி",
            "addressPlaceholder": "உள்ளூர் முகவரியை உள்ளிடவும்",
            "pincodeLabel": "அஞ்சல் பின் குறியீடு (6-இலக்கங்கள்)",
            "pincodePlaceholder": "எ.கா. 600001",
            "q6_title": "6. நீங்கள் ஆதிதிராவிடர் / பட்டியல் சாதி (SC) சமூகத்தைச் சேர்ந்தவரா?",
            "q6_desc": "NSFDC திட்டங்கள் பட்டியல் சாதி பயனாளிகளுக்கான சட்டப்பூர்வ மானிய கடன் திட்டங்களாகும்.",
            "yesSc": "✓ ஆம், நான் பட்டியல் சாதி (SC) சமூகத்தைச் சேர்ந்தவர்",
            "noSc": "✗ இல்லை, பிற சமூகம்",
            "scWarning": "⚠️ சட்டப்பூர்வ குறிப்பு: NSFDC மானிய கடன்கள் பட்டியல் சாதி (SC) குடிமக்களுக்கு மட்டுமே உரியது. படி 2 இல் சாதி சான்றிதழ் சரிபார்க்கப்படும்.",
            "q7_title": "7. கல்வித் தகுதிகள்",
            "q7_desc": "உங்கள் கல்வித் தகுதியைத் தேர்வுசெய்யவும்.",
            "selectQualification": "-- கல்வித் தகுதியைத் தேர்ந்தெடுக்கவும் --",
            "otherQualLabel": "தயவுசெய்து உங்கள் தகுதியைக் குறிப்பிடவும்:",
            "otherQualPlaceholder": "எ.கா. டிப்ளமோ, பி.காம்",
            "q8_title": "8. ஆண்டு குடும்ப வருமானம் (₹)",
            "q8_desc": "மொத்த ஆண்டு வருமானத்தை உள்ளிடவும். சட்டப்பூர்வ வரம்பு ₹ 5,00,000 / ஆண்டு.",
            "incomeLabel": "ஆண்டு குடும்ப வருமானம் (ரூபாயில்)",
            "incomePlaceholder": "எ.கா. 180000",
            "incomeLimitBadge": "சட்டப்பூர்வ உச்சவரம்பு: ₹ 5,00,000.00 / ஆண்டு",
            "incomeWarning": "⚠️ எச்சரிக்கை: ஆண்டு வருமானம் ₹ 5,00,000 உச்சவரம்பை தாண்டியுள்ளது.",
            "incomeQuick": "விரைவு தேர்வு:",
            "q9_title": "9. நீங்கள் என்ன வகையான உதவியை எதிர்பார்க்கிறீர்கள்?",
            "q9_desc": "உங்களுக்குத் தேவையான நிதி உதவி அல்லது கடன் நோக்கத்தைத் தேர்வுசெய்யவும்.",
            "selectAssistance": "-- கடன் நோக்கத்தைத் தேர்ந்தெடுக்கவும் --",
            "subBusinessTitle": "↳ வணிகம் / நிறுவன வகையைக் குறிப்பிடவும்",
            "subBusinessDesc": "உங்கள் வர்த்தக செயல்பாட்டைத் தேர்ந்தெடுக்கவும்.",
            "selectBusiness": "-- வணிகத் துறையைத் தேர்ந்தெடுக்கவும் --",
            "otherAssistLabel": "உதவித் தேவையை குறிப்பிடவும்:",
            "otherAssistPlaceholder": "எ.கா. மொபைல் பழுதுபார்க்கும் கடை",
            "otherBizLabel": "வணிக செயல்பாட்டைக் குறிப்பிடவும்:",
            "otherBizPlaceholder": "எ.கா. மசாலா பேக்கிங் யூனிட்",
            "q10_title": "10. இந்த திட்டத்திற்கு ஏற்கனவே ஏதேனும் கடன் உள்ளதா?",
            "q10_desc": "தற்போதைய நிறுவனத்திற்கு பெறப்பட்ட முந்தைய கடன் விவரங்களை வெளிப்படுத்தவும்.",
            "yesLoan": "ஆம், என்னிடம் கடன் உள்ளது",
            "noLoan": "இல்லை, இது புதிய கடன் விண்ணப்பம்",
            "existingAmountLabel": "அசல் அனுமதிக்கப்பட்ட கடன் தொகை (₹)",
            "existingAmountPlaceholder": "எ.கா. 50000",
            "outstandingAmountLabel": "தற்போதைய நிலுவைத் தொகை (₹)",
            "outstandingAmountPlaceholder": "எ.கா. 20000",
            "q11_title": "11. திட்ட மதிப்பிடப்பட்ட செலவு (₹)",
            "q11_desc": "தேவையான மொத்த மூலதன செலவை உள்ளிடவும். NSFDC 90% முதல் 95% வரை நிதியளிக்கிறது.",
            "costLabel": "மொத்த திட்டத் தேவை (ரூபாயில்)",
            "costPlaceholder": "எ.கா. 140000",
            "costQuick": "விரைவு தேர்வு:",
            "govtSharePreview": "மதிப்பிடப்பட்ட அரசு கடன் (90-95%):",
            "marginPreview": "மதிப்பிடப்பட்ட பயனாளி பங்கு (5-10%):",
            "proceedStep2": "படி 2 க்கு தொடரவும்: சாதி சான்றிதழ் OCR சரிபார்ப்பு →",
            "viewFormalApp": "📄 அதிகாரப்பூர்வ அரசு விண்ணப்பப் படிவத்தைக் காண்க",
            "validationAlert": "தொடர அனைத்து கட்டாய புலங்களையும் நிரப்பவும்."
        }
    },
    "kn": {
        "intake": {
            "title": "ನಾಗರಿಕ ರಿಯಾಯಿತಿ ಸಾಲ ಅರ್ಜಿ (ಹಂತ 1 / 4)",
            "subtitle": "ದಯವಿಟ್ಟು ಕೆಳಗಿನ 11 ಶಾಸನಬದ್ಧ ಅರ್ಹತಾ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ. ಕನ್ನಡದಲ್ಲಿ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಲು 🔊 ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಮಾತನಾಡಲು 🎙️ ಕ್ಲಿಕ್ ಮಾಡಿ.",
            "progress": "ಹಂತ 1 / 4 • ಗುರುತು ಮತ್ತು ಯೋಜನಾ ಮೌಲ್ಯಮಾಪನ",
            "listenAll": "🔊 ಪುಟದ ಸೂಚನೆಗಳನ್ನು ಆಲಿಸಿ",
            "micListening": "🎙️ ಆಲಿಸಲಾಗುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಈಗ ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ",
            "listeningActive": "ಲೈವ್ ರೆಕಾರ್ಡಿಂಗ್ ಸಕ್ರಿಯವಾಗಿದೆ",
            "clickToStop": "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
            "voiceAutoFilled": "✓ ಧ್ವನಿಯನ್ನು ಗುರುತಿಸಲಾಗಿದೆ ಮತ್ತು ಯಶಸ್ವಿಯಾಗಿ ನಮೂದಿಸಲಾಗಿದೆ!",
            "q1_title": "1. ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ಮತ್ತು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            "q1_desc": "ನಿಮ್ಮ ಅಧಿಕೃತ ಹೆಸರು ಮತ್ತು ಆಧಾರ್ ಲಿಂಕ್ ಆದ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
            "nameLabel": "ಪೂರ್ಣ ಕಾನೂನುಬದ್ಧ ಹೆಸರು",
            "namePlaceholder": "ಉದಾ. ರಾಜೇಶ್ ಕುಮಾರ್ ಎಸ್ಸಿ",
            "phoneLabel": "ಮೊಬೈಲ್ / ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
            "phonePlaceholder": "ಉದಾ. +91 98480 12345",
            "genderLabel": "ಫಲಾನುಭವಿಯ ಲಿಂಗ (ಮಹಿಳೆಯರಿಗೆ ವಿಶೇಷ 5% ರಿಯಾಯಿತಿ ಬಡ್ಡಿ ದರ)",
            "genderFemale": "ಮಹಿಳೆ (ವಿಶೇಷ 5% ರಿಯಾಯಿತಿ ಬಡ್ಡಿ ದರ)",
            "genderMale": "ಪುರುಷ (ಪ್ರಮಾಣಿತ 6.5% - 7.5% ಬಡ್ಡಿ ದರ)",
            "genderOther": "ತೃತೀಯಲಿಂಗಿ / ಇತರೆ",
            "q2_title": "2. ನಿಮ್ಮ ವಯಸ್ಸು / ಹುಟ್ಟಿದ ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
            "q2_desc": "ಕ್ಯಾಲೆಂಡರ್ ಬಳಸಿ ನಿಮ್ಮ ಜನ್ಮ ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ನೇರವಾಗಿ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ.",
            "dobLabel": "ಹುಟ್ಟಿದ ದಿನಾಂಕ (ಕ್ಯಾಲೆಂಡರ್)",
            "ageLabel": "ಲೆಕ್ಕಹಾಕಿದ ವಯಸ್ಸು",
            "yearsOld": "ವರ್ಷಗಳು",
            "q3_title": "3. ರಾಜ್ಯ / ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ",
            "q3_desc": "ಯೋಜನೆ/ವ್ಯವಹಾರ ನಡೆಯುವ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "selectState": "-- ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ --",
            "q4_title": "4. ಜಿಲ್ಲೆ",
            "q4_desc": "ಸ್ಥಳೀಯ ಎಸ್‌ಸಿ ಕಾರ್ಪೊರೇಷನ್ ಅಥವಾ ಬ್ಯಾಂಕ್ ಶಾಖೆಯ ರೂಟಿಂಗ್‌ಗಾಗಿ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "selectDistrict": "-- ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ --",
            "q5_title": "5. ಸ್ಥಳ ಮತ್ತು ಪಿನ್ ಕೋಡ್",
            "q5_desc": "ನಿಮ್ಮ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಿ ಅಥವಾ ವಿಳಾಸ ಮತ್ತು ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ.",
            "detectGps": "📍 ನನ್ನ ಪ್ರಸ್ತುತ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಪತ್ತೆಮಾಡಿ",
            "detectingGps": "ಉಪಗ್ರಹ ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
            "gpsSuccess": "✓ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪಡೆಯಲಾಗಿದೆ:",
            "manualAddress": "ಗ್ರಾಮ / ಪಟ್ಟಣ / ಬೀದಿ ವಿಳಾಸ",
            "addressPlaceholder": "ಸ್ಥಳೀಯ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
            "pincodeLabel": "ಅಂಚೆ ಪಿನ್ ಕೋಡ್ (6-ಅಂಕಿಗಳು)",
            "pincodePlaceholder": "ಉದಾ. 560001",
            "q6_title": "6. ನೀವು ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ಸಮುದಾಯಕ್ಕೆ ಸೇರಿದವರೇ?",
            "q6_desc": "NSFDC ಯೋಜನೆಗಳು ಪರಿಶಿಷ್ಟ ಜಾತಿಯ ಫಲಾನುಭವಿಗಳಿಗೆ ಮೀಸಲಾದ ಶಾಸನಬದ್ಧ ರಿಯಾಯಿತಿ ಸಾಲ ಕಾರ್ಯಕ್ರಮಗಳಾಗಿವೆ.",
            "yesSc": "✓ ಹೌದು, ನಾನು ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ಸಮುದಾಯಕ್ಕೆ ಸೇರಿದವನು/ಳು",
            "noSc": "✗ ಇಲ್ಲ, ಇತರೆ ಸಮುದಾಯ",
            "scWarning": "⚠️ ಶಾಸನಬದ್ಧ ಟಿಪ್ಪಣಿ: NSFDC ರಿಯಾಯಿತಿ ಸಾಲಗಳು ಕೇವಲ ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ನಾಗರಿಕರಿಗೆ ಮಾತ್ರ. ಹಂತ 2 ರಲ್ಲಿ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ ಪರಿಶೀಲಿಸಲಾಗುವುದು.",
            "q7_title": "7. ವಿದ್ಯಾರ್ಹತೆಗಳು",
            "q7_desc": "ನಿಮ್ಮ ಗರಿಷ್ಠ ವಿದ್ಯಾರ್ಹತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "selectQualification": "-- ವಿದ್ಯಾರ್ಹತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ --",
            "otherQualLabel": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ:",
            "otherQualPlaceholder": "ಉದಾ. ಡಿಪ್ಲೊಮಾ, ಬಿ.ಕಾಂ",
            "q8_title": "8. ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ (₹)",
            "q8_desc": "ಒಟ್ಟು ವಾರ್ಷಿಕ ಆದಾಯವನ್ನು ನಮೂದಿಸಿ. ಶಾಸನಬದ್ಧ ಮಿತಿ ₹ 5,00,000 / ವರ್ಷ.",
            "incomeLabel": "ವಾರ್ಷಿಕ ಕುಟುಂಬ ಆದಾಯ (ರೂಪಾಯಿಗಳಲ್ಲಿ)",
            "incomePlaceholder": "ಉದಾ. 180000",
            "incomeLimitBadge": "ಶಾಸನಬದ್ಧ ಮಿತಿ: ₹ 5,00,000.00 / ವರ್ಷ",
            "incomeWarning": "⚠️ ಎಚ್ಚರಿಕೆ: ವಾರ್ಷಿಕ ಆದಾಯವು ₹ 5,00,000 ಮಿತಿಯನ್ನು ಮೀರಿದೆ.",
            "incomeQuick": "ತ್ವರಿತ ಆಯ್ಕೆ:",
            "q9_title": "9. ನೀವು ಯಾವ ರೀತಿಯ ಸಹಾಯವನ್ನು ಬಯಸುತ್ತಿದ್ದೀರಿ?",
            "q9_desc": "ನಿಮಗೆ ಅಗತ್ಯವಿರುವ ಆರ್ಥಿಕ ನೆರವು ಅಥವಾ ಸಾಲದ ಉದ್ದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "selectAssistance": "-- ಸಾಲದ ಉದ್ದೇಶವನ್ನು ಆಯ್ಕೆಮಾಡಿ --",
            "subBusinessTitle": "↳ ವ್ಯವಹಾರ / ಉದ್ಯಮದ ಪ್ರಕಾರವನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ",
            "subBusinessDesc": "ನಿಮ್ಮ ವ್ಯಾಪಾರ ಚಟುವಟಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "selectBusiness": "-- ವ್ಯವಹಾರ ಕ್ಷೇತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ --",
            "otherAssistLabel": "ಸಹಾಯದ ಅಗತ್ಯವನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ:",
            "otherAssistPlaceholder": "ಉದಾ. ಮೊಬೈಲ್ ದುರಸ್ತಿ ಅಂಗಡಿ",
            "otherBizLabel": "ವ್ಯವಹಾರ ಚಟುವಟಿಕೆಯನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ:",
            "otherBizPlaceholder": "ಉದಾ. ಮಸಾಲೆ ಪ್ಯಾಕೇಜಿಂಗ್ ಘಟಕ",
            "q10_title": "10. ಈ ಯೋಜನೆಗಾಗಿ ನಿಮಗೆ ಈಗಾಗಲೇ ಯಾವುದೇ ಸಾಲವಿದೆಯೇ?",
            "q10_desc": "ಪ್ರಸ್ತುತ ಉದ್ಯಮಕ್ಕಾಗಿ ಪಡೆದ ಯಾವುದೇ ಹಿಂದಿನ ಸಾಲದ ವಿವರಗಳನ್ನು ಬಹಿರಂಗಪಡಿಸಿ.",
            "yesLoan": "ಹೌದು, ನನಗೆ ಸಾಲವಿದೆ",
            "noLoan": "ಇಲ್ಲ, ಇದು ಹೊಸ ಸಾಲದ ಅರ್ಜಿ",
            "existingAmountLabel": "ಮಂಜೂರಾದ ಸಾಲದ ಮೊತ್ತ (₹)",
            "existingAmountPlaceholder": "ಉದಾ. 50000",
            "outstandingAmountLabel": "ಪ್ರಸ್ತುತ ಬಾಕಿ ಮೊತ್ತ (₹)",
            "outstandingAmountPlaceholder": "ಉದಾ. 20000",
            "q11_title": "11. ಯೋಜನೆಯ ಅಂದಾಜು ವೆಚ್ಚ (₹)",
            "q11_desc": "ಅಗತ್ಯವಿರುವ ಒಟ್ಟು ಬಂಡವಾಳ ವೆಚ್ಚವನ್ನು ನಮೂದಿಸಿ. NSFDC 90% ರಿಂದ 95% ವರೆಗೆ ಸಾಲ ನೀಡುತ್ತದೆ.",
            "costLabel": "ಒಟ್ಟು ಯೋಜನೆಯ ವೆಚ್ಚ (ರೂಪಾಯಿಗಳಲ್ಲಿ)",
            "costPlaceholder": "ಉದಾ. 140000",
            "costQuick": "ತ್ವರಿತ ಆಯ್ಕೆ:",
            "govtSharePreview": "ಅಂದಾಜು ಸರ್ಕಾರಿ ಸಾಲ (90-95%):",
            "marginPreview": "ಅಂದಾಜು ಫಲಾನುಭವಿಯ ಪಾಲು (5-10%):",
            "proceedStep2": "ಹಂತ 2 ಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ: ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ OCR ಪರಿಶೀಲನೆ →",
            "viewFormalApp": "📄 ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಅರ್ಜಿ ನಮೂನೆಯನ್ನು ವೀಕ್ಷಿಸಿ",
            "validationAlert": "ಮುಂದುವರಿಯಲು ಎಲ್ಲಾ ಕಡ್ಡಾಯ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ."
        }
    }
}

base_dir = r"c:\Users\TRK\OneDrive\Documents\SIH 2\nsfdc-concessional-portal\frontend\src\lib\i18n"
locales_dir = r"c:\Users\TRK\OneDrive\Documents\SIH 2\nsfdc-concessional-portal\frontend\src\locales"

for code in ["en", "te", "hi", "ta", "kn", "mr", "bn", "gu"]:
    file_path = os.path.join(base_dir, f"{code}.json")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    else:
        data = {}

    target = all_languages.get(code, all_languages["en"])
    data["intake"] = target["intake"]

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    loc_file = os.path.join(locales_dir, f"{code}.json")
    if os.path.exists(locales_dir):
        with open(loc_file, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print("Language JSON dictionaries updated with verified regional translations!")
